version: '3'
services:
  db:
    image: mysql:8.0
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_DATABASE: istory
      MYSQL_USER: dangtong
      MYSQL_PASSWORD: admin123
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      #- ./data:/var/lib/mysql
volumes:
  mysql-data:
    # 비워두면 Docker가 기본 드라이버로 볼륨을 생성합니다.